barrier_spacings:
- 1.5
- 2.0
- 2.5
- 3.0
- 3.5
- 4.0
- 4.5
- 5.0
boundary_conditions:
  barrier_friction: 0.4
  basal_friction: 0.4
domain:
  aspect_ratio: 8.0
  barrier_height_factor: 2.0
  channel_width: 10.0
  debris_volume: 500.0
  slope_angle: 20.0
equations:
  dilation_angle: "\u03B2 = K\u2084(\u03C6 - \u03C6eq)                           \
    \  [Eq. 21]\n"
  drag_force: "f_d = 18\u03C6(1-\u03C6)\u03B7f/d\xB2 F\u0302(v\u209B - vf)       \
    \       [Eq. 22]\nwhere F\u0302 depends on solid fraction and grain Reynolds number\n"
  equilibrium_solid_fraction: "\u03C6eq = \u03C6\u2098/(1 + aIm)                 \
    \          [Eq. 11]\n"
  fluid_momentum: "\u03C1\u0304f(Dvf/Dt) = \u03C1\u0304fg + \u2207\xB7Tf + f_d - (1-\u03C6\
    )\u2207pf  [Eq. 6] \nwhere:\n  \u03C1\u0304f = (1-\u03C6)\u03C1f (effective fluid\
    \ density)  \n  Tf = deviatoric stress tensor of fluid phase\n"
  fluid_stress: "Tf = \u03B7f[1 + 5\u03C6/2][\u2207vf + (\u2207vf)\u1D40]        \
    \     [Eq. 10]\n"
  friction_coefficient: "\u03BC\u209A = \u03BC\u2081 + (\u03BC\u2082-\u03BC\u2081\
    )/(1+b/Im) + 5\u03C6I\u1D65/(2aIm)    [Eq. 18]\nwhere:\n  Im = \u221A(I\xB2 +\
    \ 2Iv) (mixed inertial number)\n  I = \u03B3\u0307\u209Ad\u221A(\u03C1\u209B/p')\
    \ (inertial number)  \n  Iv = \u03B7f\u03B3\u0307\u209A/p' (viscous number)\n\
    \  \u03B3\u0307\u209A = equivalent plastic shear strain rate\n"
  incompressibility: "\u2207\xB7vf = 0                                     [Eq. 9]\n"
  solid_momentum: "\u03C1\u0304\u209B(Dv\u209B/Dt) = \u03C1\u0304\u209Bg + \u2207\xB7\
    \u03C3' - f_d - \u03C6\u2207pf     [Eq. 5]\nwhere:\n  \u03C1\u0304\u209B = \u03C6\
    \u03C1\u209B (effective solid density)\n  \u03C3' = effective stress tensor of\
    \ solid phase\n  f_d = inter-phase drag force\n  \u03C6 = solid volume fraction\n\
    \  pf = pore fluid pressure\n"
  yield_surface_compaction: "fcompaction = g(\u03C6)p' - a\u03C6\xB2[(\u03B3\u0307\
    \u209A)\xB2d\xB2\u03C1\u209B + 2\u03B7f\u03B3\u0307\u209A] [Eq. 15]\nwhere:\n\
    \  g(\u03C6) = (\u03C6\u2098-\u03C6)\xB2 if \u03C6 < \u03C6\u2098, else 0\n"
  yield_surface_shear: "fshear = \u221AJ\u2082 - \u03BC\u209Ap'                  \
    \        [Eq. 17]\nwhere:\n  J\u2082 = second invariant of deviatoric stress\n\
    \  \u03BC\u209A = total friction coefficient\n  p' = mean effective stress\n"
fluid_phase:
  density: 1000.0
  viscosity: 0.001
fluidization:
  definition: "\u03BB = pbed/(pbed + \u03C3'bed)                     [Eq. 26]\nwhere:\n\
    \  \u03BB = basal fluidization ratio\n  pbed = basal pore fluid pressure  \n \
    \ \u03C3'bed = effective stress normal to bed\n"
  friction_reduction: "Ffric = \u03BCbed*\u03C3'bed = \u03BCbed*\u03C3bed*(1-\u03BB\
    )        [Eq. 25]\nEffect: Higher \u03BB \u2192 Lower bed friction \u2192 Higher\
    \ flow velocity\n"
froude_numbers:
- 2.0
- 4.0
- 6.0
impact_force:
  hydrodynamic_static: "F = \u03B1\u03C1v\xB2h + (k/2)h\xB2\u03C1||g||           \
    \        [Eq. 1]\nwhere:\n  \u03B1 = dynamic impact coefficient (= 1.0)\n  k =\
    \ static impact coefficient (= 1.0) \n  \u03C1 = debris flow density\n  v = flow\
    \ velocity at barrier\n  h = flow depth at barrier\n"
  landing_velocity: "vi = R*vr*cos\u03B8land                          [Eq. 4]\nwhere:\n\
    \  R = velocity correction factor (\u2248 1.0)\n  vr = velocity just before landing\n\
    \  \u03B8land = angle between vr and bed\n"
  point_mass_trajectory: "xi = (v\xB2launch)/(||g||cos\u03B8) * [tan\u03B8 + \u221A\
    (tan\xB2\u03B8 + 2||g||HB/(v\xB2launch*cos\u03B8))] + HB*tan\u03B8  [Eq. 3]\n\
    where:\n  xi = landing distance\n  vlaunch = launch velocity at barrier crest\n\
    \  HB = barrier height\n  \u03B8 = slope inclination\n"
metadata:
  paper_doi: https://doi.org/10.1680/jgeot.22.00199
  reference_table: Table 1, Page 4
  validation_cases:
  - sand_water_mixture
  - dry_sand
  - water_only
numerics:
  cfl_factor: 0.1
  contact_damping: 1000.0
  contact_stiffness: 100000000.0
  contact_tolerance: 1.0e-08
  max_timestep: 1.0e-05
  mesh_barrier_ratio: 0.04
  particles_per_cell: 16
  pressure_tolerance: 0.0001
  statistics_interval: 0.05
  vtk_output_interval: 0.2
performance_targets:
  convergence_rate: 1.0e-06
  memory_usage: 8.0
  stability_cfl: 0.5
  throughput: 500.0
simulation:
  barrier_height: 0.15
  barrier_positions:
  - 3.0
  - 5.0
  barrier_spacing: 2.0
  debris_volume: 500.0
  domain_height: 1.0
  domain_length: 10.0
  domain_width: 1.0
  gravity: 9.81
  slope_angle: 20.0
  total_time: 2.0
solid_phase:
  critical_solid_fraction: 0.56
  density: 2650.0
  dilatancy_param_k4: 4.7
  limiting_friction: 1.4
  particle_diameter: 0.001
  poissons_ratio: 0.3
  rheology_param_a: 1.23
  rheology_param_b: 0.31
  static_friction: 0.49
  youngs_modulus: 10.0e6
validation_data:
  flow_kinematics:
    front_velocity: 2.5
    launch_angle: 64.0
    stable_angle: 53.0
  impact_force_peak:
    dry_sand: 50.0
    sand_water: 140.0
    water: 140.0
  landing_characteristics:
    max_distance_fr2: 12.0
    max_distance_fr6: 24.0
    velocity_increase: 0.8
